apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- res/nginx-ingress-controller.yml
patchesJson6902:
- target:
    kind: Service
    name: ingress-nginx-controller
  path: res/patches.yml