---
apiVersion: v1
kind: Service
metadata:
  name: oncube-certs
spec:
  selector:
    app: oncube-certs
  type: ClusterIP
  ports:
  - port: 91
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /.well-known/acme-challenge/$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: oncube-certs
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /.well-known/acme-challenge/(.*)
        pathType: Prefix
        backend:
          service:
            name: oncube-certs
            port: 
              number: 91
---
apiVersion: batch/v1
kind: Job
metadata:
  name: oncube-certs-job
spec:
  template:
    metadata:
      labels:
        app: oncube-certs
    spec:
      containers:
      - name: certbot
        image: docker.io/certbot/certbot:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        args:
        - certonly
        - --standalone
        - -d
        - k88s.piesz.pl,k88s.piesz.app
        - -m
        - ssl@fajnie.eu
        - -n
        - --agree-tos
        # - --test-cert
        # - --dry-run
        # - -v
        volumeMounts:
        - mountPath: "/etc/letsencrypt"
          name: volume
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: oncube-certs-pvc

      restartPolicy: Never
  backoffLimit: 0