apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: oncube
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ssl@fajnie.eu
    privateKeySecretRef:
      name: oncube-ssl
    solvers:
    - http01:
        ingress:
          class: nginx