apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncube
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: oncube
        image: docker.io/pieszynski/oncube:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: WOOT
          value: "nice hello"
        - name: PEPE
          valueFrom:
            configMapKeyRef:
              name: app-env
              key: NENV
        volumeMounts:
        - name: edata
          mountPath: /app/any
      volumes:
      - name: edata
        configMap:
          name: app-data
