apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /rewrite/$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: oncube
spec:
  ingressClassName: nginx
  rules:
  - host: null.piesz.pl
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: oncube
            port: 
              number: 90
    # host: rewrite.bar.com
