kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: oncube-store
provisioner: file.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0640
  - file_mode=0640
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oncube-certs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: oncube-store
  resources:
    requests:
      storage: 250Mi