apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ing
resources:
- res/ns.yml
# - res/store.yml
- res/depl.yml
- res/svc.yml
- res/ingr.yml
- res/certs.yml
# - res/cert-job.yml
labels:
- pairs:
    res: play
    app: oncube-app
configMapGenerator:
- name: app-data
  files:
  - files/data.env
- name: app-env
  literals:
  - NENV=TEST
replicas:
- name: oncube
  count: 1
images:
- name: docker.io/nginx
  newTag: 1.21.6
- name: docker.io/nginx/unit
  newTag: 1.26.1-node16
patchesJson6902:
- target:
    version: v1
    kind: Ingress
    name: oncube
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: aks-ing.piesz.pl
    - op: add
      path: /spec/tls/0/hosts/1
      value: aks-ing.piesz.app
    - op: copy
      from: /spec/rules/0
      path: /spec/rules/1
    - op: replace
      path: /spec/rules/0/host
      value: aks-ing.piesz.pl
    - op: replace
      path: /spec/rules/1/host
      value: aks-ing.piesz.app
# - target:
#     version: v1
#     kind: Ingress
#     name: oncube-certs
#   patch: |-
#     - op: copy
#       from: /spec/rules/0
#       path: /spec/rules/1
#     - op: add
#       path: /spec/rules/0/host
#       value: 'aks-ing.piesz.pl'
#     - op: add
#       path: /spec/rules/1/host
#       value: 'aks-ing.piesz.app'